# Generated by Django 4.2.6 on 2023-10-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
